"""first migration

Revision ID: e8a41d24f6ee
Revises: 
Create Date: 2020-06-14 13:58:38.414536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a41d24f6ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('title')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language')
    )
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('translation', sa.Unicode(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('translation')
    )
    op.create_index('language_id_index', 'translations', ['language_id'], unique=False)
    op.create_table('texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('translation_id', sa.Integer(), nullable=False),
    sa.Column('book_code', sa.String(length=3), nullable=False),
    sa.Column('chapter', sa.String(length=10), nullable=False),
    sa.Column('verse', sa.Integer(), nullable=False),
    sa.Column('text', sa.UnicodeText(), nullable=False),
    sa.ForeignKeyConstraint(['book_code'], ['books.code'], ),
    sa.ForeignKeyConstraint(['translation_id'], ['translations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('book_code_index', 'texts', ['book_code'], unique=False)
    op.create_index('translation_id_index', 'texts', ['translation_id'], unique=False)
    op.create_index('verse_index', 'texts', ['book_code', 'chapter', 'verse'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('verse_index', table_name='texts')
    op.drop_index('translation_id_index', table_name='texts')
    op.drop_index('book_code_index', table_name='texts')
    op.drop_table('texts')
    op.drop_index('language_id_index', table_name='translations')
    op.drop_table('translations')
    op.drop_table('languages')
    op.drop_table('books')
    # ### end Alembic commands ###
